config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'user/omniauth_callbacks'}
  resources :boards
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  get '/login' => 'home#login'
  get '/api/getChapter'
end

app/models/board.rb
class Board < ApplicationRecord
    belongs_to :user
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.where(user: current_user).order(created_at: :desc)
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)
    respond_to do |format|
      @board.randomPhotoBackground = BoardsHelper.randomImage.sample()
      puts board_params[:bookAbbr]

      @board.book = BoardsHelper.engChangeName(board_params[:bookAbbr])
   
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      if(user_signed_in?)
        "login user"
      else
        redirect_to '/login'
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title, :content, :book, :startChapter, :startVerse, :bookAbbr, :endChapter, :endVerse, :user_id)
    end
end

app/helpers/boards_helper.rb
require 'open-uri'
require 'nokogiri'
module BoardsHelper
    extend self

    def registerBoardTime(board)
        return board.created_at.to_s[0..12]+"시"
    end
    
    def readBibleFromTo(board)
        return board.book+" "+ board.startChapter+":"+board.startVerse+" - "+board.endChapter+":"+board.endVerse
    end

    def startQT(user)
        return "QT시작 "+((Time.zone.today-user.created_at.to_date).to_i+1).to_s+ "일째"
    end

    def countQT(user)
        return user.board.count.to_s+"개의 말씀"
    end

    def bookList
        grouped_options = {
            'oldTestament' => [
                ['창세기','ge'],
                ['출애굽기','exo'],
                ['레위기','lev'],
                ['민수기','num'],
                ['신명기','deu'],
                ['여호수아','josh'],
                ['사사기','jdgs'],
                ['룻기','ruth'],
                ['사무엘상','1sm'],
                ['사무엘하','2sm'],
                ['열왕기상','1ki'],
                ['열왕기하','2ki'],
                ['역대상','1chr'],
                ['역대하','2chr'],
                ['에스라','ezra'],
                ['느헤미야','neh'],
                ['에스더','est'],
                ['욥기','job'],
                ['시편','psa'],
                ['잠언','prv'],
                ['전도서','eccl'],
                ['아가','ssol'],
                ['이사야','isa'],
                ['예레미야','jer'],
                ['예레미야 애가','lam'],
                ['에스겔','eze'],
                ['다니엘','dan'],
                ['호세아','hos'],
                ['요엘','joel'],
                ['아모스','amos'],
                ['오바댜','obad'],
                ['요나','jonah'],
                ['미가','mic'],
                ['나훔','nahum'],
                ['하박국','hab'],
                ['스바냐','zep'],
                ['학개','hag'],
                ['스가랴','zep'],
                ['말라기','mal']
            ],
            'newTestament' => [
                ['마태복음','mat'],
                ['마가복음','mark'],
                ['누가복음','luke'],
                ['요한복음','john'],
                ['사도행전','acts'],
                ['로마서','rom'],
                ['고린도전서','1cor'],
                ['고린도후서','2cor'],
                ['갈라디아서','gal'],
                ['에베소서','eph'],
                ['빌립보서','phi'],
                ['골로새서','col'],
                ['데살로니가전서','1th'],
                ['데살로니가후서','2th'],
                ['디모데전서','1tim'],
                ['디모데후서','2tim'],
                ['디도서','titus'],
                ['빌레몬서','phmn'],
                ['히브리서','heb'],
                ['야고보서','jas'],
                ['베드로전서','1pet'],
                ['베드로후서','2pet'],
                ['요한1서','1jn'],
                ['요한2서','2jn'],
                ['요한3서','3jn'],
                ['유다서','jude'],
                ['요한계시록','rev']
            ]
        }
        return grouped_options
 
    end


    def randomImage
        image = Array.new
        image.push("https://s3.ap-northeast-2.amazonaws.com/dailyquiettime/quite1.jpg")
        image.push("https://s3.ap-northeast-2.amazonaws.com/dailyquiettime/quite2.jpg")
        image.push("https://s3.ap-northeast-2.amazonaws.com/dailyquiettime/quite3.jpg")
        image.push("https://s3.ap-northeast-2.amazonaws.com/dailyquiettime/quite4.jpg")
        image.push("https://s3.ap-northeast-2.amazonaws.com/dailyquiettime/quite5.jpg")
        image.push("https://s3.ap-northeast-2.amazonaws.com/dailyquiettime/quite6.jpg")
    end

    def engChangeName(bookAbbr)
        findBook =  BookList.where(eng: bookAbbr).first
        return findBook.name
    end

    # true -> 쓰기가능
    # false -> 못씀
    def isDayWrite(user)
        writeuser = User.find(user)
        userwriteboard = writeuser.board
        unless(userwriteboard.empty?||userwriteboard == "")
            lastwrite =  userwriteboard.last().created_at.to_date
            today = Time.zone.today
            
            if(today == lastwrite)
                puts "false"
                return false
            end
        end
        return true
    end

    def countDayQuiet(board)
        return (Time.zone.today-board.created_at.to_date).to_i+1
    end

    def bibleContent(bible)

        url = "http://ibibles.net/quote.php?kor-"
        url +="#{bible.bookAbbr}/#{bible.startChapter}:#{bible.startVerse}"
        url +="-#{bible.endChapter}:#{bible.endVerse}"

        docs = Nokogiri::HTML(open(url)).text

        return docs
    end
end

app/views/boards/_form.html.erb
<div class="widthFull">
  <%= form_with(model: board, local: true,class: :newBoard) do |form| %>
  <div class="errorMessage">
    <% if board.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>
        <ul>
        <% board.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>

 <div class="newBoardBible bibleSelect">

    <div class="field newBook">
        <%= form.select :bookAbbr, BoardsHelper.bookList, id: :board_bookAbbr,:selected => "ge"%>
    </div>
    <div class="startBible">
        <div class="field newBible">
          <%= form.select :startChapter,options_for_select(1..50), id: :board_startChapter,:selected =>"1"%>
        </div>
        <div class="field newBible">
          <%= form.telephone_field :startVerse, id: :board_startVerse ,placeholder: "1"%>
        </div>
    </div>
    <div>-</div>
    <div class="endBible">
      <div class="field newBible">  
        <%= form.select :endChapter,options_for_select(1..50), id: :board_endChapter,:selected =>"1"%>
      </div>
      <div class="field newBible">
        <%= form.telephone_field :endVerse, id: :board_endVerse,placeholder: "1"%>
      </div>
      <div class="hidden_field">
          <%= form.hidden_field :user_id, id: :review_user_id, value: current_user.id%>
      </div>
    </div>
  </div>

  <div class="newBoardBOX">
    <div class="field newBoard newBoardTitle">
        <%= form.text_field :title, id: :board_title, placeholder: "제목"%>
    </div>
  
    <div class="field newBoard newBoard newBoardContent">
      <%= form.text_area :content, id: :board_content,size:100,placeholder: "말씀을 입력하세요."%>
    </div>
  </div>
  <% end %>
</div>

<script>

  $(document).ready(function(){

  var bookAbbr = "select[name='board[bookAbbr]']"
 
  var changeSelect = function (){
    var startSelector = 'select[name="board[startChapter]"]'
    var endSelector = selector = 'select[name="board[endChapter]"]'

    bookname =  $(this)[0].value;
    chapterSize = getChapterSize(bookname);

    setChapterSize(chapterSize, startSelector);
    setChapterSize(chapterSize, endSelector);
  }

  $(bookAbbr).change(changeSelect);

  var getChapterSize = function(bookname){
    var chapterSize;
    $.ajax({
      url: "/api/getChapter",
      type:"get",
      dataType: "text",
      async: false,
      data: {bookname: bookname},
      success: function(data){
        chapterSize = data;
      }
    })
    console.log("here");
    return chapterSize;
  }

  var setChapterSize = function(chapter,selector){
    $(selector).empty();
    for (i=1;i<=chapter ;i++){
      $(selector).append('<option value="'+i+'">'+i+"</option>" );  
    }
  }



  });


 
</script>

app/views/boards/edit.html.erb
<%= render '/layouts/create_header' %>
<div class="header_footer padding-side">
    <%= render 'form', board: @board %>
</div>
<style>
.container {
    width: 100%;
    justify-content: flex-start;
}
</style>
<script>
$(".formSubmit").click(function(){
    $(".newBoard").submit();
})
</script>

app/views/boards/index.html.erb
<%= render '/layouts/header' %>
<div class="header_footer">
  <div class="boardListBOX">
    <% if @boards.empty? %>
      <div class="emptyBoardList ">
        아직 <br>
        하나님의 말씀이 <br>
        없어요 <br>
      </div>
    <% end %>
    <% @boards.each do |p| %>
      <div class="boardList  moveDetailPage " id="<%=p.id%>">
        <div class="boardListHeader">
          <div>
            <p class="headerFont"><%=countDayQuiet(p)%> 일째 큐티</p>
          </div>
          <div class="empty"></div>
          <div>
               <p class="headerFont"><%=p.created_at.to_s[0..10]%></p>
          </div>

        </div>
        <div class="boardListContent">
          <div class="padding-side">"<%=p.title %>"</div>
        </div>
        <div class="boardListFooter">
            <%= BoardsHelper.readBibleFromTo(p) %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= render '/layouts/create_footer' %>
<style>
  .boardListBOX {
    height: 100%;
    overflow: scroll;
  }
  .container {
    justify-content: flex-start;
  }
  .emptyBoardList {
    height:100%;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  .headerFont {

  }
  .boardList {
    height: 113px;
    margin: 20px;
    border: 1px solid #c5c5c5;
    padding: 10px;
    display: flex;
    flex-direction: column;
    align-items: space-around;
    justify-content:space-around;

  }
  .boardListHeader {
    width:100%;
    display: flex;
    justify-content: space-between;
    font-size: 13px;
  }
  .boardListContent {
    display: flex;
    justify-content: center;
    align-items: center;
    text-align: center;
    font-size: 13px;
  }
  .boardListFooter {
    display: flex;
 
    align-items: flex-end;
    justify-content: center;
    font-size: 13px;
  }
</style>
<script>
 
  $(".moveDetailPage").click(function(){
    movepage = "boards/"+ $(this)[0].id;
    $(location).attr('href',movepage);
  })
</script>

app/views/boards/index.sample.erb
<p id="notice"><%= notice %></p>

<h1>Boards</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Startbook</th>
      <th>Startchapter</th>
      <th>Startverse</th>
      <th>Endbook</th>
      <th>Endchapter</th>
      <th>Endverse</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.title %></td>
        <td><%= board.content %></td>
        <td><%= board.startBook %></td>
        <td><%= board.startChapter %></td>
        <td><%= board.startVerse %></td>
        <td><%= board.endBook %></td>
        <td><%= board.endChapter %></td>
        <td><%= board.endVerse %></td>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board', new_board_path %>

<script>

</script>

app/views/boards/new.html.erb
<%= render '/layouts/create_header' %>
<div class="header_footer padding-side">
    <%= render 'form', board: @board %>
</div>

<script>
    var checkVali = function(data){
        if(data == "" || data == null)
            return false;
        return true;
    }

    var canSubmit = function(){
        var BoardTitle = $("#board_title")[0].value
        var BoardContent = $("#board_content")[0].value

        var bookAbbr = $("select[name='board[bookAbbr]']")[0].value
        var StartChap = $("select[name='board[startChapter]']")[0].value
        var StartVerse = $("#board_startVerse")[0].value;
        var EndChap = "select[name='board[endChapter]']"
        var EndVerse = $("#board_endVerse")[0].value;

        var flagValidation = true;

        console.log(bookAbbr,StartChap,StartVerse);

        if(!(checkVali(BoardTitle) && checkVali(BoardContent))){
            flagValidation = false;
            alert("제목 또는 내용을 채워주세요");
        }else if(!(checkVali(bookAbbr) && checkVali(StartChap) && checkVali(StartVerse) && 
            checkVali(EndChap) &&checkVali(EndVerse))){
            flagValidation = false;
            alert("구절에 안채운 부분이 있는지 확인해주세요");
        }

        return flagValidation;
    }



    $(".formSubmit").click(function(){
       if(canSubmit()){
          $(".newBoard").submit();
        }
    })
</script>

app/views/boards/show.html.erb
<%= render '/layouts/show_header' %>
<div class="header padding-side swiper-container" >
 <div class="swiper-container">
    <div class="swiper-wrapper">
      <div class="swiper-slide padding-side">
        <div class="showData">
         <div class="show showContent m-2"> 
            <%= simple_format(BoardsHelper.bibleContent(@board),class: "bible") %>
          </div>
          <div class="show showDate m-2">
            <%= BoardsHelper.readBibleFromTo(@board) %>
          </div>
        </div>
      </div>
      <div class="swiper-slide padding-side">
        <div class="padding-side widthFull">
          <div class="show showContent m-2">
            <%= simple_format(@board.content,class: "content") %>
          </div>
          <div class="show showDate m-2">
            <%= BoardsHelper.registerBoardTime(@board) %><br>
            <%= BoardsHelper.readBibleFromTo(@board) %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="swiper-pagination"></div>
</div>

<script>
  var swiper = new Swiper('.swiper-container', {
    pagination: {
      el: '.swiper-pagination',
      type: 'fraction',
    },
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },
  });
  
  showDataHeight = $(".showData")[0].clientHeight;
  setpadding = showDataHeight - 555;

  $(".showData").css("margin-top",setpadding);
 
</script>

app/views/boards/show_sample.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @board.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @board.content %>
</p>

<p>
  <strong>book:</strong>
  <%= @board.book %>
</p>

<p>
  <strong>Startchapter:</strong>
  <%= @board.startChapter %>
</p>

<p>
  <strong>Startverse:</strong>
  <%= @board.startVerse %>
</p>

<p>
  <strong>bookAbbr:</strong>
  <%= @board.bookAbbr %>
</p>

<p>
  <strong>Endchapter:</strong>
  <%= @board.endChapter %>
</p>

<p>
  <strong>Endverse:</strong>
  <%= @board.endVerse %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>